services:
  qa-server:
    build: .
    container_name: qa-server
    ports:
      - "1042:1042"
    environment:
      DB_HOST: cockroachdb
      DB_PASS: ${DB_PASS}
    env_file:
      - .env
    networks:
      - quantumauth-network
    restart: unless-stopped

networks:
  quantumauth-network:
    external: true
