SwaggerHTTPConfig:
  Port: "1042"
  Host: "0.0.0.0"
DatabaseSettings:
  Host: "localhost"
  Port: "26257"
  User: "quantum_auth_service"
  Password: ""
  Database: "quantum_auth"
  CertPAth: ""
  SSLModeDisable: false
  PoolSize: 5
