SwaggerHTTPConfig:
  Port: "1042"
  Host: "0.0.0.0"
DatabaseSettings:
  Host: "quantum-auth-10762.jxf.cockroachlabs.cloud"
  Port: "26257"
  User: "quantum_auth_service"
  Password: ""
  Database: "quantum_auth"
  CertPAth: "/etc/ssl/certs/ca-certificates.crt"
  SSLModeDisable: false
  PoolSize: 5
