SwaggerHTTPConfig:
  Port: "1042"
  Host: "0.0.0.0"

DatabaseSettings:
  Host: "localhost"
  Port: "5432"
  User: "quantum_auth_service"
  Password: "local_dev_password"
  Database: "quantumauth-db"
  CertPath: ""
  SSLModeDisable: false
  PoolSize: 5

SMTPConfig:
  Host: "smtp.protonmail.ch"
  Port: "587"
  Username: ""
  Password: ""
  Timeout: 30
  UseTLS: false
  StartTLS: true
